//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject1.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class genre
    {
        [Required(ErrorMessage = "Required")]
        public int genreid { get; set; }
        [Required(ErrorMessage = "Required")]
        public int movieid { get; set; }
        [Required(ErrorMessage = "Required")]
        public string genrename { get; set; }
    
        public virtual movies movies { get; set; }
    }
}
